
export const getExercises = (req, res) =>{
    try {
        let data = await 
    } catch (error) {
        
    }
}